[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y g++",
    "pip install --upgrade pip"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python ai.py"