[build.environment]
PYTHON_VERSION = "3.11"

[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y g++",
    "python -m pip install --upgrade pip"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python ai.py"